version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magnet-player
    ports:
      - "3000:3000"
    volumes:
      - torrent-cache:/app/server/cache
    restart: unless-stopped

volumes:
  torrent-cache:
    driver: local 